stages:
  - release

# for new tags create a release and upload to PyPI
deploy_release:
  stage: release
  image: python
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  before_script:
    - python -m pip install build setuptools_scm[toml] twine
  script:
    - python -m build --sdist --wheel --outdir dist/ .
    - python -m twine upload dist/*
  only:
    - tags
